//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotorTool_2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KotorTool_2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10125 {
            get {
                object obj = ResourceManager.GetObject("10125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\3dsmax7\scripts\NWmax\plugins\test.txt.
        /// </summary>
        internal static string _3dsmaxScriptsPath {
            get {
                return ResourceManager.GetString("3dsmaxScriptsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mdl.
        /// </summary>
        internal static string _mdl {
            get {
                return ResourceManager.GetString("_mdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mdx.
        /// </summary>
        internal static string _mdx {
            get {
                return ResourceManager.GetString("_mdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -textures.txt.
        /// </summary>
        internal static string _textures_txt {
            get {
                return ResourceManager.GetString("_textures_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tga.
        /// </summary>
        internal static string _tga {
            get {
                return ResourceManager.GetString("_tga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_floor {
            get {
                object obj = ResourceManager.GetObject("black_floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dark_with_carbon_fiber_texture_background_vector_01 {
            get {
                object obj = ResourceManager.GetObject("Dark-with-carbon-fiber-texture-background-vector-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string DoubleBackSlash {
            get {
                return ResourceManager.GetString("DoubleBackSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting model .
        /// </summary>
        internal static string Exporting_model {
            get {
                return ResourceManager.GetString("Exporting_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Model Export Location is not set.
        ///
        ///A default path has been set in the Path Manager; you may accept it or choose your own..
        /// </summary>
        internal static string ExportLocationIsNotSet {
            get {
                return ResourceManager.GetString("ExportLocationIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting textures for .
        /// </summary>
        internal static string Extracting_textures_for {
            get {
                return ResourceManager.GetString("Extracting_textures_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Complete.
        /// </summary>
        internal static string Extraction_Complete {
            get {
                return ResourceManager.GetString("Extraction_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jedi_symbol {
            get {
                object obj = ResourceManager.GetObject("Jedi_symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate folder to store exported models in.
        /// </summary>
        internal static string LocateFolderForModels {
            get {
                return ResourceManager.GetString("LocateFolderForModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdlops.exe.
        /// </summary>
        internal static string mdlops_exe {
            get {
                return ResourceManager.GetString("mdlops_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Extraction.
        /// </summary>
        internal static string Model_Extraction {
            get {
                return ResourceManager.GetString("Model_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not set.
        /// </summary>
        internal static string PathNotSet {
            get {
                return ResourceManager.GetString("PathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \TexturePacks\swpc_tex_tpa.erf.
        /// </summary>
        internal static string TexturePacksSwpcTexTpaErf {
            get {
                return ResourceManager.GetString("TexturePacksSwpcTexTpaErf", resourceCulture);
            }
        }
    }
}
