//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotorTool_2._0.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmBWMEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmBWMEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KotorTool_2._0.Forms.frmBWMEditor", typeof(frmBWMEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes GroupBox1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("GroupBox1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool GroupBox1_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("GroupBox1.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=8, Height=8}.
        /// </summary>
        public static System.Drawing.Size GroupBox1_GridSize {
            get {
                object obj = ResourceManager.GetObject("GroupBox1.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool GroupBox1_Locked {
            get {
                object obj = ResourceManager.GetObject("GroupBox1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes GroupBox1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("GroupBox1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool GroupBox1_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("GroupBox1.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("Label1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool Label1_Locked {
            get {
                object obj = ResourceManager.GetObject("Label1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Label1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label2_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("Label2.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool Label2_Locked {
            get {
                object obj = ResourceManager.GetObject("Label2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Label2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label3_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("Label3.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool Label3_Locked {
            get {
                object obj = ResourceManager.GetObject("Label3.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Label3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label4_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("Label4.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool Label4_Locked {
            get {
                object obj = ResourceManager.GetObject("Label4.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Label4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label5_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("Label5.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool Label5_Locked {
            get {
                object obj = ResourceManager.GetObject("Label5.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label5_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Label5.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label6_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("Label6.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool Label6_Locked {
            get {
                object obj = ResourceManager.GetObject("Label6.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes Label6_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Label6.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes lblNotSupported_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("lblNotSupported.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool lblNotSupported_Locked {
            get {
                object obj = ResourceManager.GetObject("lblNotSupported.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes lblNotSupported_Modifiers {
            get {
                object obj = ResourceManager.GetObject("lblNotSupported.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes MainMenu1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("MainMenu1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point MainMenu1_Location {
            get {
                object obj = ResourceManager.GetObject("MainMenu1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes MainMenu1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("MainMenu1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes MenuItem1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("MenuItem1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes MenuItem1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("MenuItem1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes MenuItem4_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("MenuItem4.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes MenuItem4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("MenuItem4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miOpenAscii_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("miOpenAscii.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miOpenAscii_Modifiers {
            get {
                object obj = ResourceManager.GetObject("miOpenAscii.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miOpenBinary_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("miOpenBinary.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miOpenBinary_Modifiers {
            get {
                object obj = ResourceManager.GetObject("miOpenBinary.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miQuit_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("miQuit.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miQuit_Modifiers {
            get {
                object obj = ResourceManager.GetObject("miQuit.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miSaveAsASCII_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("miSaveAsASCII.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miSaveAsASCII_Modifiers {
            get {
                object obj = ResourceManager.GetObject("miSaveAsASCII.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miSaveAsBinary_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("miSaveAsBinary.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes miSaveAsBinary_Modifiers {
            get {
                object obj = ResourceManager.GetObject("miSaveAsBinary.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk1_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk2x_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk2x.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk2x_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk2x.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk2x_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk2x.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk2y_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk2y.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk2y_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk2y.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk2y_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk2y.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk2z_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk2z.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk2z_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk2z.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk2z_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk2z.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk3x_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk3x.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk3x_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk3x.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk3x_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk3x.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk3y_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk3y.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk3y_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk3y.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk3y_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk3y.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk3z_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk3z.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk3z_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk3z.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk3z_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk3z.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk4x_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk4x.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk4x_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk4x.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk4x_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk4x.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk4y_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk4y.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk4y_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk4y.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk4y_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk4y.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk4z_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk4z.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk4z_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk4z.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk4z_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk4z.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk5x_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk5x.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk5x_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk5x.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk5x_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk5x.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk5y_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk5y.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk5y_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk5y.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk5y_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk5y.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk5z_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk5z.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool nudUnk5z_Locked {
            get {
                object obj = ResourceManager.GetObject("nudUnk5z.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes nudUnk5z_Modifiers {
            get {
                object obj = ResourceManager.GetObject("nudUnk5z.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes tbFilepath_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tbFilepath.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool tbFilepath_Locked {
            get {
                object obj = ResourceManager.GetObject("tbFilepath.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes tbFilepath_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tbFilepath.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes tbInfo_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("tbInfo.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool tbInfo_Locked {
            get {
                object obj = ResourceManager.GetObject("tbInfo.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes tbInfo_Modifiers {
            get {
                object obj = ResourceManager.GetObject("tbInfo.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes ToolTip1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("ToolTip1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=125,Y=17}.
        /// </summary>
        public static System.Drawing.Point ToolTip1_Location {
            get {
                object obj = ResourceManager.GetObject("ToolTip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        public static System.CodeDom.MemberAttributes ToolTip1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("ToolTip1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
